# Generated by Django 3.0.7 on 2020-06-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedVideo',
            new_name='LikedVideos',
        ),
    ]
