# Generated by Django 3.0.7 on 2020-06-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0002_auto_20200621_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedvideos',
            name='video_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
