# Generated by Django 3.0.7 on 2020-06-23 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0003_auto_20200621_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CacheResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=65535)),
                ('channel_title', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('query_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cached_videos', to='default_app.SearchQuery')),
            ],
        ),
    ]
